apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-resources
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: sample-chart
    repoURL: https://github.com/GijsvanDulmen/sample-argocd-keycloak
    targetRevision: HEAD
    helm:
      valueFiles:
      # relative to the chart
      - values-production.yaml
  syncPolicy:
    automated:
      prune: false